### ISSUE TITLE
About Ablated Diffusion Model (ADM)

### ISSUE THREAD

**Issue by yufu-wang** [Tsingularity/dift#11]
Hi, congrats on the great work!
I am interested in trying your Ablated Diffusion Model (ADM) baseline. Would you be able to share with us the implementation? Thank you.

**Comment by Tsingularity** [comment]
@yufu-wang Thanks for your interest in our work!

The DIFT_adm implementation is released [here](https://github.com/Tsingularity/dift/blob/main/src/models/dift_adm.py). But before using that, you first need to follow the instruction [here](https://github.com/Tsingularity/dift#get-benchmark-evaluation-results) to set up pre-trained model and weights.
