### ISSUE TITLE
About the use of the ft tensor

### ISSUE THREAD

**Issue by Steven-Xiong** [Tsingularity/dift#15]
Hello, thanks for your great work! I am curious about the meaning of the output feature tensor in your demo, and how it can be used in other downstream tasks as mentioned in your paper, such as image matching and segmentation? For instance, the output tensor of your demo is [2,1280,48,48], 48 are H and W dimension, and 2 refer to the input image and output image respectively, what is the meaning of 1280?

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

Your understanding of 2, 48 is correct. 1280 is the dimension of the feature vector.

Just let me know if you have any more questions.
