### ISSUE TITLE
How to use clip image feature to do correlation

### ISSUE THREAD

**Issue by wyhlovecpp** [Tsingularity/dift#16]
Hey! I have see the same question in closed issue. But that question's response is about the input image size.

What I want to ask is that clip image encoder only get a 1D token like (640). But the image size is actually 2D like (256,256) resolution.  So How do you use the aligned embedding token to do feature correlation? Maybe it doesn't have same dimension.

Looking forward to your reply!

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

For OpenCLIP, we use the intermediate layer embeddings and they are in the shape of [L, D], where L is the sequence length (number of image patches, i.e., HW) and D is the feature dimension. We get pixel-wise feature vectors via bilinearly interpolating this [H, W, D] feature map.

Let me know if you have more questions.

**Comment by wyhlovecpp** [comment]
Thanks for the reply!

**Comment by Tsingularity** [comment]
@wyhlovecpp I attached a cleaned-up version of our implementation [here](https://github.com/Tsingularity/dift/blob/main/src/models/clip.py). Hope this helps!
