### ISSUE TITLE
OSError: stabilityai/stable-diffusion-2-1 does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by murmurelo111** [Tsingularity/dift#17]
Hello!When I ran `extract_dift.py` following the readme,I came across this problem.Would you mind help me slove this?
Thanks

**Comment by Tsingularity** [comment]
Seems to be a issue of package version. Could you please try setting up the environment using `conda env create -f environment.yml` and see how it goes? This should be able to produce the same python environment as when we release the code.

This [issue](https://github.com/CompVis/stable-diffusion/issues/302) thread might also be helpful.

**Comment by murmurelo111** [comment]
> Seems to be a issue of package version. Could you please try setting up the environment using `conda env create -f environment.yml` and see how it goes? This should be able to produce the same python environment as when we release the code.
> 
> This [issue](https://github.com/CompVis/stable-diffusion/issues/302) thread might also be helpful.

Thanks for your reply!
I found that i met this problem  because i did not log in my huggingface account in my terminal.Now I have solved it.
