### ISSUE TITLE
Another related work

### ISSUE THREAD

**Issue by zhangmozhe** [Tsingularity/dift#18]
Thanks for this impressive work. Microsoft has previously proposed the CoCosNet series of works (Cross-domain Correspondence Learning for Exemplar-based Image Translation, CoCosNet v2: Full-Resolution Correspondence Learning for Image Translation) that establishes dense correspondence for cross-domain images using GANs. The idea is also about cultivating the hidden knowledge learned alongside the generative process. Could you please have a look at the two papers and mention them in your work?  

Thanks.

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

Thanks for suggesting the related works! Unfortunately, we just submitted our neurips camera ready revision, which was due last Friday. We'll try to find a way to include them in our next arxiv version.

Hope this helps!
