### ISSUE TITLE
Implementation of Ablated Diffusion Model (ADM)

### ISSUE THREAD

**Issue by z-jiaming** [Tsingularity/dift#19]
Congratulations for your great work!

I'm fascinated with Ablated Diffusion Model (ADM) baseline, could you please release your code?

Thanks a lot!!!

**Comment by Tsingularity** [comment]
Thanks for your interest in our work!

The DIFT_adm implementation is released [here](https://github.com/Tsingularity/dift/blob/main/src/models/dift_adm.py). But before using that, you first need to follow the instruction [here](https://github.com/Tsingularity/dift#get-benchmark-evaluation-results) to set up pre-trained model and weights.
