### ISSUE TITLE
Hi, Can you please provide me with a basic example of the viewpoint change?

### ISSUE THREAD

**Issue by adityapandey9** [Tsingularity/dift#22]
Thank you for this awesome project. I have seen on the webpage page it is said that it changes the viewpoint of the image object as well. There is no such demo given. Please provide me with a basic example of how I can do this if possible. I really appreciate any help you can provide.

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work! Could you please elaborate more on the "it changes the viewpoint of the image object"? I don't rememebr we had such things on our webpage.

**Comment by adityapandey9** [comment]
Hi @Tsingularity thank you for the reply. I am talking about this. Let me know if I am wrong here because it uses some datasets to have different viewpoints. 
![Screenshot 2024-05-08 at 10 46 05 AM](https://github.com/Tsingularity/dift/assets/24506908/0f8835dc-727c-4cfb-9f30-50d6e08fcc15)
