### ISSUE TITLE
The training code and Geometric Correspondence demo code

### ISSUE THREAD

**Issue by lyp19** [Tsingularity/dift#5]
Hi, I want to ask when The training code and Geometric Correspondence demo code will be released?

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

DIFT just takes the intermediate features on noisy $x_t$, so there's no training involved. 

I'll keep you updated when we release the code for HPatches experiments. But it should be easy to reproduce our results following the descriptions in Sec. 6.1 of our paper. [CAPS](https://github.com/qianqianwang68/caps#feature-extraction)'s codebase could also be helpful.

Feel free to let us know if there's anything else we can help with.
