### ISSUE TITLE
How to choose features from OpenCLIP?

### ISSUE THREAD

**Issue by ZY123-GOOD** [Tsingularity/dift#6]
Hello! Thanks for your great work.
I don't know how to use OpenCLIP to find correspondences. Could you please share these codes?\
Thanks again.

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

The original OpenCLIP codebase didn't support input image size larger than the training resolution (at least it was still the case when we wrote our paper), so we follow the common practice and manually interpolate position encoding to support larger input resolution. This [pull request](https://github.com/mlfoundations/open_clip/pull/416) could be very helpful as a reference.

Feel free to let us know if you have more questions.

**Comment by Tsingularity** [comment]
@ZY123-GOOD I attached a cleaned-up version of our implementation [here](https://github.com/Tsingularity/dift/blob/main/src/models/clip.py). Hope this helps!
