### ISSUE TITLE
Question about Prompt for stable diffusion to obtain Feature maps 

### ISSUE THREAD

**Issue by IFICL** [Tsingularity/dift#7]
Thanks authors for the nice work. I have some questions about obtain feature map from stable diffusion model. According to your code, if I read correctly, you will need a text prompt, e.g., " a photo of cat" to obtain the diffusion feature. 

I wonder how authors obtain the text prompts when evaluating on the label progation benchmarks or other benchmarks. Do you need to annonate them in a rough way?

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

For DIFT_sd, on homography estimation and label propagation tasks, we use null prompt (empty string). See more implementation details in Appendix A of the paper.

**Comment by IFICL** [comment]
Thanks for the infromation. I will close the issue
