### ISSUE TITLE
How to reimplement segmentation with DIFT

### ISSUE THREAD

**Issue by dongxuyue** [Tsingularity/dift#9]
Hello,
Great work!
I would like to know how I would go about using DIFT in segmentation task that mentioned in the paper.
![image](https://github.com/Tsingularity/dift/assets/73353239/2342bd9b-e37f-4c84-a36c-9b3a3a89b162)

Thank you very much!

**Comment by Tsingularity** [comment]
Hi, thanks for your interest in our work!

Our evaluation on DAVIS basically follow the same practice as in DINO's [code](https://github.com/facebookresearch/dino#evaluation-davis-2017-video-object-segmentation), i.e., replacing the DINO features with DIFT.

Feel free to let us know if you have more questions!

**Comment by Tsingularity** [comment]
@dongxuyue I just pushed a cleaned-up version of our evaluation code. Hope this helps!
